layout: lecture
author:
- family: Lawrence
  given: Neil D.
  gscholar: r3SJcvoAAAAJ
  institute: Amazon Cambridge and University of Sheffield
  twitter: lawrennd
  orcid: 0000-0001-9258-1030
  url: http://inverseprobability.com
ipynb: True
venue: "Gaussian Process Summer School, Sheffield"
postdir: ../../../mlatcl/gpss/_lectures/
slidedir: ../../../mlatcl/gpss/slides/
notedir: ../../../mlatcl/gpss/_notes/
notebookdir: ../../../mlatcl/gpss/_notebooks/
