layout: lecture
author:
- family: Lawrence
  given: Neil D.
  gscholar: r3SJcvoAAAAJ
  institute: University of Cambridge
  twitter: lawrennd
  orcid: 0000-0001-9258-1030
  url: http://inverseprobability.com
ipynb: True
venue: "Gaussian Process Summer School"
postsdir: ../../../mlatcl/gpss/_lectures/
slidesdir: ../../../mlatcl/gpss/slides/
notesdir: ../../../mlatcl/gpss/_notes/
notebooksdir: ../../../mlatcl/gpss/_notebooks/
writediagramsdir: .
diagramsdir: ./slides/diagrams/
transition: None
time:
ghub:
- organization: lawrennd
  repository: talks
  branch: gh-pages
  directory: _gpss