layout: lecture
author:
- family: Lawrence
  given: Neil D.
  gscholar: r3SJcvoAAAAJ
  institute: University of Cambridge
  twitter: lawrennd
  orcid: 0000-0001-9258-1030
  url: http://inverseprobability.com
ipynb: True
venue: "Gaussian Process Summer School"
postdir: ../../../mlatcl/gpss/_lectures/
slidedir: ../../../mlatcl/gpss/slides/
notedir: ../../../mlatcl/gpss/_notes/
notebookdir: ../../../mlatcl/gpss/_notebooks/
transition: None
time:
ghub:
- organization: lawrennd
  repository: talks
  branch: gh-pages
  directory: _gpss