BASE=deep-gps-II
MAKEFILESDIR=/Users/neil/lawrennd/lamd/lamd/makefiles
INCLUDESDIR=/Users/neil/lawrennd/lamd/lamd/includes
SCRIPTDIR=/Users/neil/lawrennd/lamd/lamd/scripts
include $(MAKEFILESDIR)/make-talk-flags.mk
include $(MAKEFILESDIR)/make-talk.mk
